Login screen
Capstone-Alterra/flutter-raih-peduli pull request #14
Opened 2023-11-21 18:08 UTC by mochagatha

2023-11-22 18:12 UTC, GydeonZ requested changes
Tolong di perbaiki berdasarkan review saya

2023-11-22 18:12 UTC, GydeonZ commented on assets/2 User.png
ga icon mending make svg aja

2023-11-22 18:12 UTC, GydeonZ commented on lib/screen/view/signin_dan_signup/masuk_atau_daftar.dart
> +    final widthMediaQuery = MediaQuery.of(context).size.width;
mending make `Size size = MediaQuery.of(context).size;` jadi ini mencakup untuk widht sma height juga

2023-11-22 18:12 UTC, GydeonZ commented on lib/screen/view/signin_dan_signup/sign_in.dart
> +    final viewModel = Provider.of<SignInViewModel>(context, listen: false);
untuk semua provider dimasukin ke initstate ga kyk gini
`void initState() {
  super.initState();
  final viewModel = Provider.of<SignInViewModel>(context, listen: false);
}`

2023-11-23 06:46 UTC, mochagatha commented on assets/2 User.png
ok

2023-11-23 06:47 UTC, mochagatha commented on lib/screen/view/signin_dan_signup/masuk_atau_daftar.dart
> +    final widthMediaQuery = MediaQuery.of(context).size.width;
alasan saya memakai MediaQuery.of(context).size.width; karena saya ingin mengambil panjang dari device yang di gunakan user

2023-11-23 06:48 UTC, mochagatha commented on lib/screen/view/signin_dan_signup/sign_in.dart
> +    final viewModel = Provider.of<SignInViewModel>(context, listen: false);
ok

2023-11-24 07:32 UTC, GydeonZ approved these changes

2023-11-24 08:00 UTC, Repaiii approved these changes

2023-11-24 08:15 UTC, merged